apiVersion: 1

datasources:
  - name: QuestDB
    type: postgres
    access: proxy
    url: questdb:8812
    user: admin
    database: qdb
    isDefault: false
    editable: true
    secureJsonData:
      password: ${GRAFANA_QUESTDB_PW:-quest}
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: false
      maxOpenConns: 4
      maxIdleConns: 2
      connMaxLifetime: 14400

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
